# Generated by Django 5.1.2 on 2024-11-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartdetail_quantity_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to='orders.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='MNCLF7OP', max_length=10),
        ),
    ]
