# Generated by Django 5.1.2 on 2024-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='WNNIQ7HI', max_length=10),
        ),
    ]
